[build]
target = "thumbv4t-none-eabi"

[unstable]
build-std = ["core"]

[target.thumbv4t-none-eabi]
rustflags = [
    "-Ztrap-unreachable=no",
    "-Clinker=arm-none-eabi-ld",
    "-Clink-arg=-Tlinker/boot.ld",
]
